<?php
// Variables
return [
  'creatorName' => 'Edudeve.com',
  'creatorUrl' => 'https://edudeve.com',
  'templateName' => 'Edudeve',
  'templateSuffix' => 'Edudeve',
  'templateVersion' => '1.0.0',
  'templateFree' => false,
  'templateDescription' => 'A Powerfull Software solution for the educational company',
  'templateKeyword' => 'dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5',
  'licenseUrl' => 'https://themeforest.net/licenses/standard',
  'livePreview' => 'https://demos.pixinvent.com/frest-html-admin-template/landing/',
  'productPage' => 'https://1.envato.market/frest_admin',
  'support' => 'https://pixinvent.ticksy.com/',
  'moreThemes' => 'https://1.envato.market/pixinvent_portfolio',
  'documentation' => 'https://demos.pixinvent.com/frest-html-admin-template/documentation',
  'generator' => '',
  'changelog' => 'https://demos.pixinvent.com/frest/changelog.html',
  'repository' => 'https://github.com/pixinvent/frest-admin-dashboard-template-src',
  'gitAuthor' => 'pixinvent',
  'gitRepo' => 'frest-admin-dashboard-template-src',
  'facebookUrl' => 'https://www.facebook.com/pixinvents/',
  'twitterUrl' => 'https://twitter.com/pixinvents',
  'githubUrl' => 'https://github.com/pixinvent',
  'dribbbleUrl' => 'https://dribbble.com/pixinvent',
  'instagramUrl' => 'https://www.instagram.com/pixinvents/',
];
